import { ChainId, StrategyBlock } from '../../constants';
import { AssetType, IStrategy } from '../../types';

export const strategies: IStrategy[] = [
  {
    id: 1,
    url: 'bridgeworld-claim',
    comingSoon: false,
    imageSrc: './img/atlas-mine.jpg',
    title: 'Claim Atlas Mine rewards',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: `Use this strategy when you want to periodically claim $MAGIC earned during a vested release.`,
    blocks: [StrategyBlock.Arbitrum_Bridgeworld_Claim],
  },
  {
    id: 2,
    url: 'bridgeworld-claim',
    comingSoon: false,
    imageSrc: './img/atlas-mine2.jpg',
    title: 'Claim and send Atlas Mine rewards',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: `Use this strategy when you want to periodically claim $MAGIC earned during a vested release and then immediately send some $MAGIC to a different address.`,
    blocks: [StrategyBlock.Arbitrum_Bridgeworld_Claim, StrategyBlock.Arbitrum_Magic_Send],
  },
  {
    id: 3,
    url: '',
    comingSoon: true,
    title: 'Magic Dragon DAO',
    imageSrc: './img/magic-dragon.jpg',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: ``,
    blocks: [],
  },
  {
    id: 4,
    url: '',
    comingSoon: true,
    title: 'BattleFly',
    imageSrc: './img/battlefly.jpg',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: ``,
    blocks: [],
  },
  {
    id: 5,
    url: '',
    comingSoon: true,
    title: 'Tales of Elleria',
    imageSrc: './img/tales-of-alleria.jpg',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: ``,
    blocks: [],
  },
  {
    id: 6,
    url: '',
    comingSoon: true,
    title: 'SmithyDAO',
    imageSrc: './img/smithy.jpg',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: ``,
    blocks: [],
  },
  {
    id: 7,
    url: '',
    comingSoon: true,
    title: 'Bridgeworld (Ivory Tower)',
    imageSrc: './img/ivory-tower.jpg',
    assetType: AssetType.Ethereum,
    chainId: ChainId.arbitrum,
    description: ``,
    blocks: [],
  },
];
